#!/usr/bin/env bash

os=$(uname)
dir="$(dirname "$0")"

echo "[*] Proceed to pwn your device with ipwnder for macOS or iOS"
echo "[*] ipwnder for iOS: https://github.com/LukeZGD/Legacy-iOS-Kit/wiki/Pwning-Using-Another-iOS-Device"
echo "[*] Waiting for device in pwned DFU mode"

while ! ("$dir"/irecovery -q 2>/dev/null | grep "PWND: ipwnder"); do
    sleep 1
done
